### PR TITLE
MNT bump codecov uploader

### PR DESCRIPTION
**Pull request by adrinjalali**
Closes https://github.com/skops-dev/skops/pull/408

### CODE REVIEW

**Comment by adrinjalali** [comment]
Finally green. Seems like we needed a new codecov token. Not sure what all those matplotlib issues are though, and they don't make the CI fail, and I can reproduce locally.

**Comment by adrinjalali** [comment]
cc @BenjaminBossan

**Review by BenjaminBossan — APPROVED** [review]
Thanks for figuring this out.

> Not sure what all those matplotlib issues are though

What issues?

**Comment by adrinjalali** [comment]
It's there in the 3.9 build in the test log. But we can ignore it it seems.

**Pull request merged**
