### PR TITLE
MNT: Update repo URL of sklearn nightly build, fix sparse matrix persistence issue

### PR DESCRIPTION
**Pull request by BenjaminBossan**
See [this comment](https://github.com/scikit-learn/scikit-learn/issues/25273#issuecomment-1609430993).

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Hmm, I'm really stumped about this error. First of all, even though pickle does not have the problem, saving and loading with scipy (which skops uses under the hood) has the same issue:

```python
>>> from scipy.sparse import load_npz, save_npz
>>> from scipy import sparse
>>> x = sparse.csr_matrix((3, 4))
>>> x.has_canonical_format
True
>>> x._has_canonical_format
True
>>> save_npz('/tmp/sparse_matrix.npz', x)
>>> y = load_npz('/tmp/sparse_matrix.npz')
>>> y._has_canonical_format
AttributeError: 'csr_matrix' object has no attribute '_has_canonical_format'
```

So in a way it's already broken in scipy, but probably it's not considered a problem there, since it's a private attribute.

What surprises me, however, is that the issue only occurs now. The change in scipy is already [10 years old](https://github.com/scipy/scipy/blame/899f4efbcd8020b538bd97eb54353b3249af6e43/scipy/sparse/_compressed.py#L1083), so this is not caused by a new scipy version. So then I thought that there was a change in sklearn recently, but the corresponding attribute was also last touched a long time ago ([5 years](https://github.com/scikit-learn/scikit-learn/blame/98f21a928c2820268477751afc36e8a174f60441/sklearn/feature_extraction/text.py#L1677)), therefore, this is also not an explanation.

The most likely explanation has thus to be some change in [`scipy.sparse.diags`](https://github.com/scipy/scipy/blame/2e16ec5bc62b7b7db21b37b838fc771c7d232006/scipy/sparse/_construct.py#L73-L196), which is what is being called by sklearn and has been changed in the last month. I suspect that somewhere inside that function, the attribute is indirectly created, but I cannot pinpoint out where and what recent change affected this.

Anyway, I'll push a solution that will ensure that the private attributes are present on the loaded object iff they were present on the original object. This is achieved by remembering if the attribute was there when storing the state. If it was, when loading the object, `loaded.has_canonical_format` is accessed, which, as a side effect, creates the private attributes. This is a somewhat ugly solution, but I think it is the "most correct" solution short of fixing the problem inside of scipy.

**Comment by BenjaminBossan** [comment]
Okay, CI is green, ready for review @skops-dev/maintainers. Until this, or a different fix, is merged, CI will be red for everyone :/

**Comment by adrinjalali** [comment]
This to me is similar to the flags issue we had with numpy, i.e. it doesn't affect the actual values in the matrix, and only gives an information about how it's stored.

I think we can safely just ignore this attribute instead of trying to save it.

**Comment by BenjaminBossan** [comment]
So the suggestion would be to add a special case to the tests to explicitly remove those two arguments?

**Comment by adrinjalali** [comment]
yeah I'd just remove them.

**Comment by BenjaminBossan** [comment]
@adrinjalali pls take another look.

**Review by adrinjalali — APPROVED** [review]
Nice!

**Comment by jot-s-bindra** [comment]
Its not related to this commit
I just wanted your help in setting up environment in local machine
```
git clone git@github.com:jot-s-bindra/skops.git
git init
git checkout -b new-feature
conda create -c conda-forge -n skops python=3.10
conda activate skops
python -m pip install -e ".[tests,docs]"
conda install -c conda-forge pre-commit
pre-commit install
pytest
```
during pytest i am recieving variable declare errors , modules not installed errors like
ERROR examples/plot_california_housing.py - KeyError: 'HF_HUB_TOKEN'
ERROR examples/plot_hf_hub.py - KeyError: 'HF_HUB_TOKEN'
ERROR examples/plot_intelex.py - KeyError: 'HF_HUB_TOKEN'
ERROR scripts/clean_skops.py - OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
ERROR spaces/skops_model_card_creator/app.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/create.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/edit.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/gethelp.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/start.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/tasks.py - ModuleNotFoundError: No module named 'streamlit'

**Comment by adrinjalali** [comment]
In order to run hugging face related commands, you need to have your token present in `HF_HUB_TOKEN` environment variable.

The `spaces` folder is not for most users. If you want to run it locally, you need to have its dependencies including `streamlit` installed.

**Pull request merged**
