### PR TITLE
FIX: fixed `get_log_level` when level = 3

### PR DESCRIPTION
**Pull request by EdAbati**
When working on #343, I stumbled upon this tiny bug: if one sets the log level equal to 3, the CLI raises a `IndexError` exception. 

Steps to reproduce:
```sh
$ skops convert test.pkl -vvv
Traceback (most recent call last):
 ...
IndexError: list index out of range
```

I added the fix in this PR and also a small test. :)

### CODE REVIEW

**Review by BenjaminBossan — APPROVED** [review]
LGTM, thanks for catching this. Ping @E-Aho

**Comment by jot-s-bindra** [comment]
Its not related to this commit
I just wanted your help in setting up environment in local machine
```
git clone git@github.com:jot-s-bindra/skops.git
git init
git checkout -b new-feature
conda create -c conda-forge -n skops python=3.10
conda activate skops
python -m pip install -e ".[tests,docs]"
conda install -c conda-forge pre-commit
pre-commit install
pytest
```
during pytest i am recieving variable declare errors , modules not installed errors like
ERROR examples/plot_california_housing.py - KeyError: 'HF_HUB_TOKEN'
ERROR examples/plot_hf_hub.py - KeyError: 'HF_HUB_TOKEN'
ERROR examples/plot_intelex.py - KeyError: 'HF_HUB_TOKEN'
ERROR scripts/clean_skops.py - OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
ERROR spaces/skops_model_card_creator/app.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/create.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/edit.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/gethelp.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/start.py - ModuleNotFoundError: No module named 'streamlit'
ERROR spaces/skops_model_card_creator/tasks.py - ModuleNotFoundError: No module named 'streamlit'

**Comment by EdAbati** [comment]
HI @jot-s-bindra , I am happy to help! 
since it is not related to this PR, could you make an new issue about the problem you are having? We will move the conversation over there :)

**Review by adrinjalali — APPROVED** [review]

**Comment by BenjaminBossan** [comment]
@adrinjalali Feel free to merge, I think this one just slipped under the radar.

**Pull request merged**
