### PR TITLE
MNT refresh expired token

### PR DESCRIPTION
**Pull request by adrinjalali**
HF invalidated our token again, so here's another one.

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Yes, tokens were invalidated last week: https://huggingface.co/blog/space-secrets-disclosure

I wonder if we should just deactivate all the tests that are based on HF tokens? Maybe just skip them unless an env var is set, and only run those tests locally? Not sure how relevant these parts of the skops functionality are overall vs the other parts, you probably know better.

**Comment by adrinjalali** [comment]
codecov action from version 4 automatically switches to tokenless upload, which is useless 😠 

https://docs.codecov.com/docs/codecov-uploader#supporting-token-less-uploads-for-forks-of-open-source-repos-using-codecov

**Comment by adrinjalali** [comment]
issue on codecov side: https://github.com/codecov/codecov-action/issues/1469

**Comment by adrinjalali** [comment]
> I wonder if we should just deactivate all the tests that are based on HF tokens? Maybe just skip them unless an env var is set, and only run those tests locally? Not sure how relevant these parts of the skops functionality are overall vs the other parts, you probably know better.

Yeah those are I think the least used features. We can slowly deprecated them maybe. I would be in support of that. Can do in another PR.

@BenjaminBossan this is now ready for a merge :)

**Pull request merged**
