### PR TITLE
`MNT/MAINT` upgrading isort to 5.12.0

### LINKED ISSUE #293: pre-commit fails due to isort upgrade
When committing something the pre-commit hook fails with the below error. That's due to the latest `isort` upgrade to `5.12.0`. Please check their [commit](https://github.com/PyCQA/isort/commit/0d219a6e0b49b7f84ef0702b2387d5e14299bb8e) changing the `pip-shims` version. 

## Environment
* python `3.10.9`
* poetry `1.3.2`

## Log
```log
(skops_py310) omar@dell:~/repos/mine/skops$ git commit -m "#224: getting {numpy,scipy}.ufuncs with different versions"
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/omar/.cache/pre-commit/repokfh5jmuf/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/omar/.cache/pre-commit/repokfh5jmuf
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/omar/.cache/pre-commit/repokfh5jmuf/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/home/omar/.cache/pre-commit/repokfh5jmuf/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/omar/.cache/pre-commit/repokfh5jmuf/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-v_6hc82v/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-v_6hc82v/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /home/omar/.cache/pre-commit/pre-commit.log

```

### PR DESCRIPTION
**Pull request by omar-araboghli**
Closes #293

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
Thanks for providing a fix so quickly.

Before going ahead, could you please describe how I could replicate the initial problem? I tried creating a fresh environment as described in `CONTRIBUTING.rst` (except I used conda instead of mamba) and it worked without your fix. Is it something that only surfaces when using poetry? From the commit you linked, it's not clear to me why that would break pre-commit.

Independent of that, I think we can still merge it, I just want to better understand the issue.

**Comment by omar-araboghli** [comment]
@BenjaminBossan Thanks for your feedback! Interesting... These are the reproduction steps:

* Create a conda environment via PyCharm with python `3.10`
* python -m pip install -e ".[tests,docs]"
* conda install pre-commit
* pre-commit install

Maybe I should have followed `CONTRIBUTING.rst` more strictly, but as you already said. It's safer to merge and make skops up-to-date with its dependencies.

**Comment by BenjaminBossan** [comment]
> * Create a conda environment via PyCharm with python `3.10`

Interesting, this seems to be the only step that differs. Do you have an idea what PyCharm could be doing differently here that would cause the issue? I have `conda 23.1.0` but I don't think the conda version should be the cause.

**Comment by omar-araboghli** [comment]
From the error log I understood that an older version of isort is being installed based on isort's recent `pyproject.yaml`. I also couldn't find any different behavior while creating a conda environment by PyCharm so far. So I freshly cloned the repo and exactly followed the contributing guidelines this time and still getting the same error :open_mouth:.

**Review by BenjaminBossan — APPROVED** [review]

**Comment by BenjaminBossan** [comment]
Heh, strange. Still, I merged since it shouldn't hurt and there may be other PyCharm users out there who run into the same issue (note that it seems like they backported the fix to 5.11 too: https://github.com/PyCQA/isort/releases/tag/5.11.5).

For the @skops-dev/maintainers and others who work on the repo, please make sure to update pre-commit, not sure if it does so automatically.

**Pull request merged**
