### PR TITLE
[don't merge] Test hfh v0.27.0.rc0

### PR DESCRIPTION
**Pull request by hanouticelina**

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
@hanouticelina There has been a big refactor of the CI recently in #451. That's why this PR can't be run.

@adrinjalali do you think it's still necessary to check skops against HFH?

**Comment by adrinjalali** [comment]
> @adrinjalali do you think it's still necessary to check skops against HFH?

I don't think so. They're not maintained and we've removed some functionalities and deprecated some (to be removed in the coming release).

I was actually debating whether to keep them or not, since we haven't really had any usage of the hub front, and removing the dependency (or making it optional) would make the package significantly lighter. WDYT?

**Comment by BenjaminBossan** [comment]
Then I lean towards removing the dependency. For most dependencies, I might have told users: We have tested until version x.y.z, there is no support for newer versions. But given the nature of the HFH package, it's probably a better idea to remove the support completely.

**Comment by hanouticelina** [comment]
thanks @BenjaminBossan, noted! I will close this PR then

**Pull request closed without merging**
