### PR TITLE
ENH Add details tag in methods

### LINKED ISSUE #107: Add detail tag to new sections
Following up the discussion in #106:

> I had an idea regarding detail tags, maybe that would solve the issue (though in a separate PR): How about we add an additional argument to all `add_*` methods like `detail_tag=False`. If `True`, everything that is added is automatically enclosed in a detail tag.

Just to be clear, the section heading should be rendered normally but the section content would be folded.

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Fixes #107

When passing `details_tag=True` for figures or tables, those are now
folded.

Note that this does not work for content added via the add method, since
that content relies on the existing template. Therefore, to change that,
the template has to be changed.

To see the results, look here:

* [Plot](https://huggingface.co/skops-ci/hf_hub_example-fcc9ddb0-1904-4bb6-ae49-e7fd1d2d589c#confusion-matrix)
* [Tables](https://huggingface.co/skops-ci/hf_hub_example-fcc9ddb0-1904-4bb6-ae49-e7fd1d2d589c#hyperparameter-search-results)

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
@adrinjalali ready for review

**Review by adrinjalali — COMMENTED** [review]
Thanks for the PR. I'm happy with the implementation, but I think the fact that the `details` tag does it, is an implementation detail. WDYT of calling the argument something like `expandable` instead?

**Comment by BenjaminBossan** [comment]
> WDYT of calling the argument something like `expandable` instead?

Yes, we can rename the argument. I wanted to use something that would have 0% chance of being actually intended as a section title. If you think "expandable" fits the bill, we can take that. I also thought about "folded" (like "code folding"), just to throw something else out there.

**Comment by adrinjalali** [comment]
yeah folded seems a better one to me.

**Review by adrinjalali — APPROVED** [review]

**Pull request merged**
