### PR TITLE
Testing CI

### PR DESCRIPTION
**Pull request by BenjaminBossan**
Don't merge

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
For latest sklearn, tests fail with:

> from sklearn.utils import parse_version
> E   ImportError: cannot import name 'parse_version' from 'sklearn.utils' (/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/sklearn/utils/__init__.py)

**Comment by adrinjalali** [comment]
@BenjaminBossan you working on a fix?

**Comment by BenjaminBossan** [comment]
So changing the import a bit seems to fix the issue. CI is still red thanks to codecov.

The PR that broke the import is https://github.com/scikit-learn/scikit-learn/pull/28486.

In an associated thread, someone wrote some wise words: https://github.com/scikit-learn/scikit-learn/pull/26686#pullrequestreview-1516731282

**Review by adrinjalali — APPROVED** [review]
We've hard coded the token for codecov in plain text, why is it empty lolol. Thanks for the fix @BenjaminBossan

**Pull request merged**
